[package]
name = "the-way"
version = "0.5.0"
edition = "2018"
authors = ["Ninjani"]
description = "A code snippets manager for your terminal"
repository = "https://github.com/out-of-cheese-error/the-way"
readme = "README.md"
license = "MIT"
keywords = ["cli", "code", "snippets"]
categories = ["command-line-utilities"]
exclude = [
    "tests/",
    "ci/",
    ".travis.yml",
]

[dependencies]
# Argument parsing
structopt = "0.3.15"

# Configuration management
confy = "0.4.0"
directories-next = "1.0.1"

# Error management
eyre = "0.6.0"
color-eyre = { version = "0.5.0", default-features = false}
thiserror = "1.0.20"

# Database related
sled = "0.32.1"
bincode = "1.3.1"

# Serializing
serde = "1.0.114"
serde_json = "1.0.56"
serde_derive = "1.0.114"
serde_yaml = "0.8.13"

# Parsing and manipulating dates
chrono = { version = "0.4.13", features = ["serde"] }
chrono-english = "0.1.4"

# Taking user input and showing progress
dialoguer = "0.6.2"
indicatif = "0.15.0"

# Fuzzy search
skim = "0.8.2"

# Copy to clipboard
copypasta-ext = "0.3.0"

# Terminal syntax highlighting
syntect = { version = "4.2.0", default-features = false, features = ["default-fancy"] }
hex = "0.4.2"

# Sync to Gist/GitLab
reqwest = { version = "0.10.6", features = ["json", "blocking", "rustls-tls"], default-features = false }

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.4"
tempfile = "3.1.0"
rexpect = "0.4.0"

#[target.'cfg(target_os = "macos")'.dev-dependencies]
#clipboard = "0.5.0"
